language: node_js
node_js:
  - "11.7.0"
install: 
  - npm install
  - mkdir temp
  - cd temp
  - curl -L -o sketch.zip http://www.sketchapp.com/download/sketch.zip
  - unzip -q sketch.zip

script:
  - gulp SVG 
